FROM ros:jazzy-ros-base

# Install dependencies
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*

# Create workspace
WORKDIR /ros_ws
COPY ./ros_ws/src ./src

# Build the workspace
RUN . /opt/ros/jazzy/setup.sh && colcon build

# Source the workspace in the entrypoint
ENTRYPOINT ["/bin/bash", "-c", "source /opt/ros/jazzy/setup.bash && source install/setup.bash && ros2 run greeter_pkg talker"]
